name: Build Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install VICE emulator (for c1541)
      run: |
        sudo apt-get update
        sudo apt-get install -y vice
        
    - name: Install Prog8 compiler and 64tass
      run: |
        # Install 64tass from Ubuntu repositories
        sudo apt-get install -y 64tass
        
        # Download and install prog8 compiler
        wget https://github.com/irmen/prog8/releases/download/v11.4.1/prog8c-11.4.1-all.jar
        sudo mkdir -p /opt/prog8
        sudo mv prog8c-11.4.1-all.jar /opt/prog8/
        
        # Create wrapper script
        sudo tee /usr/local/bin/prog8c << 'EOF'
        #!/bin/bash
        java -jar /opt/prog8/prog8c-11.4.1-all.jar "$@"
        EOF
        sudo chmod +x /usr/local/bin/prog8c
        
    - name: Test font conversion
      run: make fonts
      
    - name: Test dictionary conversion
      run: make dict
      
    - name: Test individual program builds
      run: |
        make TARGET=hello
        make TARGET=hello_bitmap
        make TARGET=hello_resource
        make TARGET=ime_test
        make TARGET=modem_test
        
    - name: Test D64 creation
      run: make d64
      
    - name: Verify release files
      run: |
        make release-files
        ls -la crt/kanji_magicdesk_basic.crt
        ls -la prog8/build/c64jp_programs.d64
        
    - name: Build summary
      run: |
        echo "✅ Build completed successfully"
        echo "📦 CRT size: $(stat -c%s crt/kanji_magicdesk_basic.crt) bytes"
        echo "💾 D64 size: $(stat -c%s prog8/build/c64jp_programs.d64) bytes"
        echo "🎯 Programs built: hello, hello_bitmap, hello_resource, ime_test, modem_test"